import type { RoadmapNodeData } from "../types/roadmap";

export const dsaTopics: RoadmapNodeData[] = [
  {
    id: "arrays",
    title: "Arrays & Hashing",
    color: "#3b82f6",
    icon: "boxes",
    problems: 47,
    completed: 0,
    progress: 0,
    difficulty: "Easy",
    estimatedHours: 12,
    description: "Learn arrays, hashing, prefix sums and basic data manipulation.",
    resources: [
      {
        title: "NeetCode Arrays",
        url: "https://neetcode.io/",
        type: "youtube",
      },
      {
        title: "LeetCode Arrays",
        url: "https://leetcode.com/problemset/",
        type: "practice",
      },
    ],
    children: [],
  },

  {
    id: "strings",
    title: "Strings",
    color: "#8b5cf6",
    icon: "type",
    problems: 31,
    completed: 0,
    progress: 0,
    difficulty: "Easy",
    estimatedHours: 8,
    description: "Master string manipulation, pattern matching and parsing.",
    resources: [],
    children: [],
  },

  {
    id: "linked-list",
    title: "Linked List",
    color: "#ec4899",
    icon: "git-branch",
    problems: 24,
    completed: 0,
    progress: 0,
    difficulty: "Easy",
    estimatedHours: 6,
    description: "Singly, doubly and circular linked lists.",
    resources: [],
    children: [],
  },

  {
    id: "trees",
    title: "Trees",
    color: "#22c55e",
    icon: "tree",
    problems: 42,
    completed: 0,
    progress: 0,
    difficulty: "Medium",
    estimatedHours: 18,
    description: "Binary Trees, BST, AVL, Traversals and more.",
    resources: [],
    children: [],
  },

  {
    id: "graphs",
    title: "Graphs",
    color: "#f97316",
    icon: "network",
    problems: 38,
    completed: 0,
    progress: 0,
    difficulty: "Hard",
    estimatedHours: 20,
    description: "BFS, DFS, Topological Sort, MST and Shortest Path.",
    resources: [],
    children: [],
  },
];